services:
    deployer.templates:
        class: WebtownPhp\DeployerBundle\Services\TemplateList
    app.kuma.template_generator:
        class: WebtownPhp\DeployerBundle\Deployer\WebtownKunstmaanDeployer
        arguments: ["@twig", "@kernel"]
        tags:
          - { name: deployer.template }
